<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Controllers\security\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Controllers\security\**" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="Controllers\security\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Controllers\security\**" />
    </ItemGroup>

</Project>
